# .github/workflows/cd.yml

name: Continuous Deployment
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

  workflow_dispatch:

jobs:
  cd-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Update Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: update # Checkout the 'update' branch where the model lives

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Project Dependencies and Hugging Face CLI
        run: |
          pip install -r requirements.txt
          pip install "huggingface_hub[cli]"

      - name: Set PATH for Hugging Face CLI 🛠️
        # This command appends the local user-installed bin directory (~/.local/bin)
        # to the GitHub Actions PATH environment, making 'huggingface-cli' available.
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Deployment To Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: make deploy HF_TOKEN=$HF_TOKEN
        # This step installs the CLI so it's available in the PATH for the next step.
        

